version: '3'
services:
  network-example-service:
    image: apishytristancontainer.azurecr.io/streamlit_d:latest
    container_name: kind_nash
    restart: always
    ports:
      - "8501:8501"
  my-custom-app:
    image: apishytristancontainer.azurecr.io/api_d:1.0
    container_name: admiring_hermann
    restart: always
    ports:
      - "8000:8000"
